version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transaction_app
    ports:
      - "8081:8081" # Mapea el puerto de la app al host
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI: http://keycloak:9595/realms/sof-project
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_ID: sof-project-2025
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET: 5WzDQNGdrDZvAFyPenl8oRmi6ihvll5C
    depends_on:
      - db
      - keycloak

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: SOFKADB
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak
    ports:
      - "8081:8081" # Cambia el puerto externo para evitar conflictos con la app en 8080
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: db
      KC_DB_URL_DATABASE: SOFKADB
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: 12345
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
    depends_on:
      - db
    command: start --hostname keycloak

volumes:
  postgres_data: